
REM This is a file auto-generated by rosinstall for windows
REM refer to http://www.ros.org/wiki/win_rosinstall
REM for more information.

@REM Utility variables
@doskey wordpad="C:\Program Files\Windows NT\Accessories\wordpad.exe" $1
@doskey notepp="C:\Program Files (x86)\Notepad++\notepad++.exe" $1

@REM Could not find windows sdk or visual studio, please
@REM install and configure by hand [Windows SDK/Visual Studio]
@REM call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x86 /Release
@REM "C:\Program Files\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" x86
@REM "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" x86
@REM Colours are a god awful ugly canary yellow or vomit green
@color 7

