/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file C:\work\ws\src\common_msgs\diagnostic_msgs\srv\SelfTest.srv
 *
 */


#ifndef DIAGNOSTIC_MSGS_MESSAGE_SELFTEST_H
#define DIAGNOSTIC_MSGS_MESSAGE_SELFTEST_H

#include <ros/service_traits.h>


#include <diagnostic_msgs/SelfTestRequest.h>
#include <diagnostic_msgs/SelfTestResponse.h>


namespace diagnostic_msgs
{

struct SelfTest
{

typedef SelfTestRequest Request;
typedef SelfTestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SelfTest
} // namespace diagnostic_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::diagnostic_msgs::SelfTest > {
  static const char* value()
  {
    return "74c9372c870a76da4fc2b3973978b898";
  }

  static const char* value(const ::diagnostic_msgs::SelfTest&) { return value(); }
};

template<>
struct DataType< ::diagnostic_msgs::SelfTest > {
  static const char* value()
  {
    return "diagnostic_msgs/SelfTest";
  }

  static const char* value(const ::diagnostic_msgs::SelfTest&) { return value(); }
};


// service_traits::MD5Sum< ::diagnostic_msgs::SelfTestRequest> should match 
// service_traits::MD5Sum< ::diagnostic_msgs::SelfTest > 
template<>
struct MD5Sum< ::diagnostic_msgs::SelfTestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::diagnostic_msgs::SelfTest >::value();
  }
  static const char* value(const ::diagnostic_msgs::SelfTestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::diagnostic_msgs::SelfTestRequest> should match 
// service_traits::DataType< ::diagnostic_msgs::SelfTest > 
template<>
struct DataType< ::diagnostic_msgs::SelfTestRequest>
{
  static const char* value()
  {
    return DataType< ::diagnostic_msgs::SelfTest >::value();
  }
  static const char* value(const ::diagnostic_msgs::SelfTestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::diagnostic_msgs::SelfTestResponse> should match 
// service_traits::MD5Sum< ::diagnostic_msgs::SelfTest > 
template<>
struct MD5Sum< ::diagnostic_msgs::SelfTestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::diagnostic_msgs::SelfTest >::value();
  }
  static const char* value(const ::diagnostic_msgs::SelfTestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::diagnostic_msgs::SelfTestResponse> should match 
// service_traits::DataType< ::diagnostic_msgs::SelfTest > 
template<>
struct DataType< ::diagnostic_msgs::SelfTestResponse>
{
  static const char* value()
  {
    return DataType< ::diagnostic_msgs::SelfTest >::value();
  }
  static const char* value(const ::diagnostic_msgs::SelfTestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DIAGNOSTIC_MSGS_MESSAGE_SELFTEST_H
