set(LOG4CXX_VERSION 0.10.0 CACHE INTERNAL "")
set(LOG4CXX_COMPILER cl CACHE INTERNAL "")
set(LOG4CXX_COMPILER_VERSION 16.0 CACHE INTERNAL "")
set(LOG4CXX_BUILD_MODE Release CACHE INTERNAL "")

get_filename_component(LOG4CXX_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)

set(LOG4CXX_INCLUDE_DIR "${LOG4CXX_CMAKE_DIR}/../../../include" CACHE PATH "Log4cxx include directory")
set(LOG4CXX_INCLUDE_DIRS "${LOG4CXX_INCLUDE_DIR}" CACHE INTERNAL "")
set(LOG4CXX_LIBRARY_DIRS "${LOG4CXX_CMAKE_DIR}/../../../lib" CACHE INTERNAL "")
set(LOG4CXX_LIBRARIES "${LOG4CXX_CMAKE_DIR}/../../../lib/log4cxx.lib" CACHE INTERNAL "")