/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file C:\work\ws\src\rosbridge_suite\rosbridge_library\srv\TestMultipleRequestFields.srv
 *
 */


#ifndef ROSBRIDGE_LIBRARY_MESSAGE_TESTMULTIPLEREQUESTFIELDS_H
#define ROSBRIDGE_LIBRARY_MESSAGE_TESTMULTIPLEREQUESTFIELDS_H

#include <ros/service_traits.h>


#include <rosbridge_library/TestMultipleRequestFieldsRequest.h>
#include <rosbridge_library/TestMultipleRequestFieldsResponse.h>


namespace rosbridge_library
{

struct TestMultipleRequestFields
{

typedef TestMultipleRequestFieldsRequest Request;
typedef TestMultipleRequestFieldsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TestMultipleRequestFields
} // namespace rosbridge_library


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosbridge_library::TestMultipleRequestFields > {
  static const char* value()
  {
    return "6cce9fb727dd0f31d504d7d198a1f4ef";
  }

  static const char* value(const ::rosbridge_library::TestMultipleRequestFields&) { return value(); }
};

template<>
struct DataType< ::rosbridge_library::TestMultipleRequestFields > {
  static const char* value()
  {
    return "rosbridge_library/TestMultipleRequestFields";
  }

  static const char* value(const ::rosbridge_library::TestMultipleRequestFields&) { return value(); }
};


// service_traits::MD5Sum< ::rosbridge_library::TestMultipleRequestFieldsRequest> should match 
// service_traits::MD5Sum< ::rosbridge_library::TestMultipleRequestFields > 
template<>
struct MD5Sum< ::rosbridge_library::TestMultipleRequestFieldsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosbridge_library::TestMultipleRequestFields >::value();
  }
  static const char* value(const ::rosbridge_library::TestMultipleRequestFieldsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosbridge_library::TestMultipleRequestFieldsRequest> should match 
// service_traits::DataType< ::rosbridge_library::TestMultipleRequestFields > 
template<>
struct DataType< ::rosbridge_library::TestMultipleRequestFieldsRequest>
{
  static const char* value()
  {
    return DataType< ::rosbridge_library::TestMultipleRequestFields >::value();
  }
  static const char* value(const ::rosbridge_library::TestMultipleRequestFieldsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosbridge_library::TestMultipleRequestFieldsResponse> should match 
// service_traits::MD5Sum< ::rosbridge_library::TestMultipleRequestFields > 
template<>
struct MD5Sum< ::rosbridge_library::TestMultipleRequestFieldsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosbridge_library::TestMultipleRequestFields >::value();
  }
  static const char* value(const ::rosbridge_library::TestMultipleRequestFieldsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosbridge_library::TestMultipleRequestFieldsResponse> should match 
// service_traits::DataType< ::rosbridge_library::TestMultipleRequestFields > 
template<>
struct DataType< ::rosbridge_library::TestMultipleRequestFieldsResponse>
{
  static const char* value()
  {
    return DataType< ::rosbridge_library::TestMultipleRequestFields >::value();
  }
  static const char* value(const ::rosbridge_library::TestMultipleRequestFieldsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSBRIDGE_LIBRARY_MESSAGE_TESTMULTIPLEREQUESTFIELDS_H
