/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file C:\work\ws\src\rosbridge_suite\rosbridge_library\srv\TestResponseOnly.srv
 *
 */


#ifndef ROSBRIDGE_LIBRARY_MESSAGE_TESTRESPONSEONLY_H
#define ROSBRIDGE_LIBRARY_MESSAGE_TESTRESPONSEONLY_H

#include <ros/service_traits.h>


#include <rosbridge_library/TestResponseOnlyRequest.h>
#include <rosbridge_library/TestResponseOnlyResponse.h>


namespace rosbridge_library
{

struct TestResponseOnly
{

typedef TestResponseOnlyRequest Request;
typedef TestResponseOnlyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TestResponseOnly
} // namespace rosbridge_library


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosbridge_library::TestResponseOnly > {
  static const char* value()
  {
    return "da5909fbe378aeaf85e547e830cc1bb7";
  }

  static const char* value(const ::rosbridge_library::TestResponseOnly&) { return value(); }
};

template<>
struct DataType< ::rosbridge_library::TestResponseOnly > {
  static const char* value()
  {
    return "rosbridge_library/TestResponseOnly";
  }

  static const char* value(const ::rosbridge_library::TestResponseOnly&) { return value(); }
};


// service_traits::MD5Sum< ::rosbridge_library::TestResponseOnlyRequest> should match 
// service_traits::MD5Sum< ::rosbridge_library::TestResponseOnly > 
template<>
struct MD5Sum< ::rosbridge_library::TestResponseOnlyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosbridge_library::TestResponseOnly >::value();
  }
  static const char* value(const ::rosbridge_library::TestResponseOnlyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosbridge_library::TestResponseOnlyRequest> should match 
// service_traits::DataType< ::rosbridge_library::TestResponseOnly > 
template<>
struct DataType< ::rosbridge_library::TestResponseOnlyRequest>
{
  static const char* value()
  {
    return DataType< ::rosbridge_library::TestResponseOnly >::value();
  }
  static const char* value(const ::rosbridge_library::TestResponseOnlyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosbridge_library::TestResponseOnlyResponse> should match 
// service_traits::MD5Sum< ::rosbridge_library::TestResponseOnly > 
template<>
struct MD5Sum< ::rosbridge_library::TestResponseOnlyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosbridge_library::TestResponseOnly >::value();
  }
  static const char* value(const ::rosbridge_library::TestResponseOnlyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosbridge_library::TestResponseOnlyResponse> should match 
// service_traits::DataType< ::rosbridge_library::TestResponseOnly > 
template<>
struct DataType< ::rosbridge_library::TestResponseOnlyResponse>
{
  static const char* value()
  {
    return DataType< ::rosbridge_library::TestResponseOnly >::value();
  }
  static const char* value(const ::rosbridge_library::TestResponseOnlyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSBRIDGE_LIBRARY_MESSAGE_TESTRESPONSEONLY_H
