# Generated by CMake 2.8.7

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

SET(Boost_IMPORT_TARGETS_ADDED TRUE)

# Create imported target boost_date_time-mt-shared
ADD_LIBRARY(boost_date_time-mt-shared SHARED IMPORTED)

# Create imported target boost_date_time-mt-shared-debug
ADD_LIBRARY(boost_date_time-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_thread-mt-shared
ADD_LIBRARY(boost_thread-mt-shared SHARED IMPORTED)

# Create imported target boost_thread-mt-shared-debug
ADD_LIBRARY(boost_thread-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_regex-mt-shared
ADD_LIBRARY(boost_regex-mt-shared SHARED IMPORTED)

# Create imported target boost_regex-mt-shared-debug
ADD_LIBRARY(boost_regex-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_serialization-mt-shared
ADD_LIBRARY(boost_serialization-mt-shared SHARED IMPORTED)

# Create imported target boost_serialization-mt-shared-debug
ADD_LIBRARY(boost_serialization-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_wserialization-mt-shared
ADD_LIBRARY(boost_wserialization-mt-shared SHARED IMPORTED)

# Create imported target boost_wserialization-mt-shared-debug
ADD_LIBRARY(boost_wserialization-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_math_tr1-mt-shared
ADD_LIBRARY(boost_math_tr1-mt-shared SHARED IMPORTED)

# Create imported target boost_math_tr1-mt-shared-debug
ADD_LIBRARY(boost_math_tr1-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_math_tr1f-mt-shared
ADD_LIBRARY(boost_math_tr1f-mt-shared SHARED IMPORTED)

# Create imported target boost_math_tr1f-mt-shared-debug
ADD_LIBRARY(boost_math_tr1f-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_math_tr1l-mt-shared
ADD_LIBRARY(boost_math_tr1l-mt-shared SHARED IMPORTED)

# Create imported target boost_math_tr1l-mt-shared-debug
ADD_LIBRARY(boost_math_tr1l-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_math_c99-mt-shared
ADD_LIBRARY(boost_math_c99-mt-shared SHARED IMPORTED)

# Create imported target boost_math_c99-mt-shared-debug
ADD_LIBRARY(boost_math_c99-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_math_c99f-mt-shared
ADD_LIBRARY(boost_math_c99f-mt-shared SHARED IMPORTED)

# Create imported target boost_math_c99f-mt-shared-debug
ADD_LIBRARY(boost_math_c99f-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_math_c99l-mt-shared
ADD_LIBRARY(boost_math_c99l-mt-shared SHARED IMPORTED)

# Create imported target boost_math_c99l-mt-shared-debug
ADD_LIBRARY(boost_math_c99l-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_random-mt-shared
ADD_LIBRARY(boost_random-mt-shared SHARED IMPORTED)

# Create imported target boost_random-mt-shared-debug
ADD_LIBRARY(boost_random-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_graph-mt-shared
ADD_LIBRARY(boost_graph-mt-shared SHARED IMPORTED)

# Create imported target boost_graph-mt-shared-debug
ADD_LIBRARY(boost_graph-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_python-mt-shared
ADD_LIBRARY(boost_python-mt-shared SHARED IMPORTED)

# Create imported target boost_python-mt-shared-debug
ADD_LIBRARY(boost_python-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_system-mt-shared
ADD_LIBRARY(boost_system-mt-shared SHARED IMPORTED)

# Create imported target boost_system-mt-shared-debug
ADD_LIBRARY(boost_system-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_prg_exec_monitor-mt-shared
ADD_LIBRARY(boost_prg_exec_monitor-mt-shared SHARED IMPORTED)

# Create imported target boost_prg_exec_monitor-mt-shared-debug
ADD_LIBRARY(boost_prg_exec_monitor-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_unit_test_framework-mt-shared
ADD_LIBRARY(boost_unit_test_framework-mt-shared SHARED IMPORTED)

# Create imported target boost_unit_test_framework-mt-shared-debug
ADD_LIBRARY(boost_unit_test_framework-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_filesystem-mt-shared
ADD_LIBRARY(boost_filesystem-mt-shared SHARED IMPORTED)

# Create imported target boost_filesystem-mt-shared-debug
ADD_LIBRARY(boost_filesystem-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_iostreams-mt-shared
ADD_LIBRARY(boost_iostreams-mt-shared SHARED IMPORTED)

# Create imported target boost_iostreams-mt-shared-debug
ADD_LIBRARY(boost_iostreams-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_program_options-mt-shared
ADD_LIBRARY(boost_program_options-mt-shared SHARED IMPORTED)

# Create imported target boost_program_options-mt-shared-debug
ADD_LIBRARY(boost_program_options-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_signals-mt-shared
ADD_LIBRARY(boost_signals-mt-shared SHARED IMPORTED)

# Create imported target boost_signals-mt-shared-debug
ADD_LIBRARY(boost_signals-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_wave-mt-shared
ADD_LIBRARY(boost_wave-mt-shared SHARED IMPORTED)

# Create imported target boost_wave-mt-shared-debug
ADD_LIBRARY(boost_wave-mt-shared-debug SHARED IMPORTED)

# Load information for each installed configuration.
GET_FILENAME_COMPONENT(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
FILE(GLOB CONFIG_FILES "${_DIR}/Boost-*.cmake")
FOREACH(f ${CONFIG_FILES})
  INCLUDE(${f})
ENDFOREACH(f)

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
